// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASFuE9XDr_oDiWmHF5TGwTTU0ecQ_Dnbs',
    appId: '1:857087373950:web:e09d238d182817cc189e2f',
    messagingSenderId: '857087373950',
    projectId: 'fir-tutorial-25396',
    authDomain: 'fir-tutorial-25396.firebaseapp.com',
    storageBucket: 'fir-tutorial-25396.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jHpdW_fPppDEh7XjhFdU8o_p95ZcU-s',
    appId: '1:857087373950:android:50a767c9d0076b0d189e2f',
    messagingSenderId: '857087373950',
    projectId: 'fir-tutorial-25396',
    storageBucket: 'fir-tutorial-25396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5qG36ywmb3TMTX--6REQ1nUv6faobfQ',
    appId: '1:857087373950:ios:ccad86f9049bc85f189e2f',
    messagingSenderId: '857087373950',
    projectId: 'fir-tutorial-25396',
    storageBucket: 'fir-tutorial-25396.appspot.com',
    iosBundleId: 'com.example.localSell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr5qG36ywmb3TMTX--6REQ1nUv6faobfQ',
    appId: '1:857087373950:ios:8549ecf56fcd1a55189e2f',
    messagingSenderId: '857087373950',
    projectId: 'fir-tutorial-25396',
    storageBucket: 'fir-tutorial-25396.appspot.com',
    iosBundleId: 'com.example.localSell.RunnerTests',
  );
}
